import { expect, test } from 'vitest'
import { files } from './_repo.js'

// Defends: Alexia.md's own tripwire. Rust is confined to installer, updates, tray and
// hotkey, plus holding the keychain (D153) and reading the temperature sensors (`temps.rs`),
// neither of which decides anything. Rust nobody here can debug at 3am is worse than no Rust,
// and the budget is the only thing that notices it creeping.
//
// 300 until the sensors, which are about 25 lines; it moved by 30 for them, which is a few
// lines of slack and not a new allowance. The next thing that wants room has to argue for it.
//
// 380 for the genie's snapshot (`snapshot.rs`, about 45 lines): WKWebView's `takeSnapshot`, the
// one way to get a picture of the page, which the Settings and Activity sheets are bent into
// their tab from. Every way without it was tried first — copies of the sheet cut into strips
// stuttered and showed steps. It decides nothing and keeps nothing: one rectangle in, one JPEG
// out. Again a few lines of slack, not an allowance.
//
// 435 for keeping core alive (`start` in `main.rs`, about 55 lines): the windows wait on the
// starting page until core's port answers, and a core that stops on its own is started again
// with growing waits. Only this process can do either — it is the one that spawns core and holds
// the vault line it is handed — and without them a slow start was a white window for good and a
// core that died was an Alexia that looked open and answered nothing. It decides nothing: it
// knocks on a port and starts the same command again.
//
// 485 for Apple's own Liquid Glass over the switchers (`glass.rs`, about 50 lines): an
// NSGlassEffectView laid over a page element, passing clicks through, on macOS 26 and later.
// Only a native view can bend what is behind it in the web view; the page keeps its own glass
// everywhere else. It decides nothing: it puts a view where the page says and moves it.
//
// 520 for the glass done Apple's way: the chosen symbol drawn inside it, a tint, a springy move,
// and the trackpad's click as the switch lands (`glass.rs`, 35 more lines).
//
// 595 for the edge of the screen while Alexia drives it (`control_overlay` in `main.rs`, about
// 70 lines): a window over the whole display that cannot be clicked, left out of screenshots,
// and on a Mac a panel that can never take the keyboard — a key window there would swallow the
// keys Alexia is typing into another app, and only native code can say *never key*. With it,
// ⌥Esc to stop, handled here so the way out does not depend on the page still answering. It
// decides nothing: the page says when to show it, and a stop is the page's own Stop pressed.
//
// 660 for compute mode (`main.rs`, about 60 lines): only the shell can destroy its windows,
// unregister assistant hotkeys and retain the tray after setup. It decides nothing: core says
// when the windows may go, what the status line reads and whether Pause says Resume; a tray
// click is one line down the existing pipe. Pausing, unpairing, switching roles and what idle
// means remain TypeScript; the native transport lives outside this shell and its budget.

const BUDGET = 660

test(`rust-line-budget: hand-written Rust in src-tauri stays under ${BUDGET} lines`, () => {
  const hand = files(['src-tauri/src/**/*.rs']).filter((f) => !/@generated|Generated by/.test(f.text))

  const counted = hand.map((f) => ({
    path: f.path,
    lines: f.text.split('\n').filter((l) => l.trim() !== '' && !l.trim().startsWith('//')).length,
  }))
  const total = counted.reduce((n, f) => n + f.lines, 0)

  expect(
    total,
    `Rust budget blown. Move logic into the TypeScript core:\n${counted
      .map((f) => `${f.path}  ${f.lines}`)
      .join('\n')}`,
  ).toBeLessThanOrEqual(BUDGET)
})
