import { expect, test } from 'vitest'
import { files } from './_repo.js'

// Defends: Alexia.md's own tripwire. Rust is confined to installer, updates, tray and
// hotkey, plus holding the keychain (D153) and reading the temperature sensors (`temps.rs`),
// neither of which decides anything. Rust nobody here can debug at 3am is worse than no Rust,
// and the budget is the only thing that notices it creeping.
//
// 300 until the sensors, which are about 25 lines; it moved by 30 for them, which is a few
// lines of slack and not a new allowance. The next thing that wants room has to argue for it.
//
// 380 for the genie's snapshot (`snapshot.rs`, about 45 lines): WKWebView's `takeSnapshot`, the
// one way to get a picture of the page, which the Settings and Activity sheets are bent into
// their tab from. Every way without it was tried first — copies of the sheet cut into strips
// stuttered and showed steps. It decides nothing and keeps nothing: one rectangle in, one JPEG
// out. Again a few lines of slack, not an allowance.

const BUDGET = 380

test(`rust-line-budget: hand-written Rust in src-tauri stays under ${BUDGET} lines`, () => {
  const hand = files(['src-tauri/src/**/*.rs']).filter((f) => !/@generated|Generated by/.test(f.text))

  const counted = hand.map((f) => ({
    path: f.path,
    lines: f.text.split('\n').filter((l) => l.trim() !== '' && !l.trim().startsWith('//')).length,
  }))
  const total = counted.reduce((n, f) => n + f.lines, 0)

  expect(
    total,
    `Rust budget blown. Move logic into the TypeScript core:\n${counted
      .map((f) => `${f.path}  ${f.lines}`)
      .join('\n')}`,
  ).toBeLessThanOrEqual(BUDGET)
})
