import { expect, test } from 'vitest'
import { files } from './_repo.js'

// Defends: Alexia.md's own tripwire. Rust is confined to installer, updates, tray and
// hotkey. Rust nobody here can debug at 3am is worse than no Rust, and the budget is the
// only thing that notices it creeping.

const BUDGET = 300

test(`rust-line-budget: hand-written Rust in src-tauri stays under ${BUDGET} lines`, () => {
  const hand = files(['src-tauri/src/**/*.rs']).filter((f) => !/@generated|Generated by/.test(f.text))

  const counted = hand.map((f) => ({
    path: f.path,
    lines: f.text.split('\n').filter((l) => l.trim() !== '' && !l.trim().startsWith('//')).length,
  }))
  const total = counted.reduce((n, f) => n + f.lines, 0)

  expect(
    total,
    `Rust budget blown. Move logic into the TypeScript core:\n${counted
      .map((f) => `${f.path}  ${f.lines}`)
      .join('\n')}`,
  ).toBeLessThanOrEqual(BUDGET)
})
