FROM rust:1.91.1-bookworm@sha256:c1e5f19e773b7878c3f7a805dd00a495e747acbdc76fb2337a4ebf0418896b33 AS builder

RUN cargo install iroh-relay --version '=1.3.0' --locked --features server --root /opt/iroh

FROM python:3.12.11-slim-bookworm@sha256:519591d6871b7bc437060736b9f7456b8731f1499a57e22e6c285135ae657bf7
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY --from=builder /opt/iroh/bin/iroh-relay /usr/local/bin/iroh-relay
COPY run_service.py healthcheck.py ./
USER 10001:10001
EXPOSE 3340 9090
ENTRYPOINT ["python", "/app/run_service.py", "relay"]
